import React from "react";
import { AbsoluteFill, useCurrentFrame, interpolate, Easing } from "remotion";
import { SipTrunkingPage, CreateTrunkDrawer, CreateUriModal } from "./TrunkKit";
import { NewConsoleShell } from "./NewConsoleShell";
import { PhoneNumbersScreen } from "../OnboardingVoiceAgents";
import { INTER_FAMILY } from "../fonts";
import { VoiceAgentsPage, BuildModal, AgentPage, ConfigurationBody, ConfigurationVoiceBody, DeploymentBody, NewNumberModal } from "./XaiKit";

// Scenes of the xAI video on the kit. Frames are relative to each shot's Sequence (30 fps).
const ease = (f: number, a: number, b: number) => interpolate(f, [a, b], [0, 1], { easing: Easing.inOut(Easing.cubic), extrapolateLeft: "clamp", extrapolateRight: "clamp" });
export const NUMBER = "+1 701 719 8695"; const XAI = "xAI (SpaceXAI)"; const ADDR = "sip:sip.voice.x.ai;transport=tls";
const type = (f: number, s: string, from: number, until: number) => (until <= from ? (f >= from ? s : "") : s.slice(0, Math.floor(ease(f, from, until) * s.length)));

// ---- Plivo ----
export const PlListBeat: React.FC<{ clickAt: number }> = ({ clickAt }) => { const f = useCurrentFrame(); const slide = ease(f, clickAt + 6, clickAt + 26); return <AbsoluteFill><SipTrunkingPage pulseAt={clickAt} dim={slide > 0.05} drawer={slide > 0 ? <CreateTrunkDrawer showPlatform v2 right={-760 * (1 - slide)} /> : null} /></AbsoluteFill>; };
export const PlPlatformBeat: React.FC<{ openAt: number; hoverAt: number; pickAt: number }> = ({ openAt, hoverAt, pickAt }) => { const f = useCurrentFrame(); return <AbsoluteFill><SipTrunkingPage dim drawer={<CreateTrunkDrawer showPlatform v2 name="xAI" platformOpen={f >= openAt && f < pickAt} platformHover={f >= hoverAt ? XAI : ""} platform={f >= pickAt ? XAI : ""} />} /></AbsoluteFill>; };
export const PlNameBeat: React.FC<{ typeFrom: number; typeUntil: number }> = ({ typeFrom, typeUntil }) => { const f = useCurrentFrame(); return <AbsoluteFill><SipTrunkingPage dim drawer={<CreateTrunkDrawer showPlatform v2 name={type(f, "xAI", typeFrom, typeUntil)} typing nameFocus />} /></AbsoluteFill>; };
export const PlUriBeat: React.FC<{ modalAt: number; typeFrom?: number; typeUntil?: number; createdAt?: number }> = ({ modalAt, typeFrom = 9999, typeUntil = 9999, createdAt = 9999 }) => {
  const f = useCurrentFrame(); const created = f >= createdAt;
  return <AbsoluteFill><SipTrunkingPage dim toast={created ? "Origination URI created successfully" : undefined} drawer={<><CreateTrunkDrawer showPlatform platform={XAI} name="xAI" uri={created ? "xAI" : ""} uriAddress={ADDR} />{f >= modalAt && !created ? <CreateUriModal platform="xAI" address={ADDR} name={type(f, "xAI", typeFrom, typeUntil)} typing={f >= typeFrom && f < typeUntil + 10} /> : null}</>} /></AbsoluteFill>;
};
export const PlLinkBeat: React.FC<{ openAt: number; pickAt: number; createAt?: number }> = ({ openAt, pickAt, createAt = 9999 }) => { const f = useCurrentFrame(); return <AbsoluteFill><SipTrunkingPage dim toast={f >= createAt ? "Inbound trunk created successfully" : undefined} drawer={<CreateTrunkDrawer showPlatform v2 platform={XAI} name="xAI" uri="xAI" uriAddress={ADDR} numbers={[[NUMBER, ""]]} numbersOpen={f >= openAt && f < pickAt + 16} numbersHover={f >= openAt + 10 ? NUMBER : ""} linked={f >= pickAt ? [NUMBER] : []} />} /></AbsoluteFill>; };
// the console today: picking the xAI platform fills the Primary URI straight into the drawer (no modal)
export const PlUriFilledBeat: React.FC<{ filledAt?: number; createAt?: number }> = ({ filledAt = 0, createAt = 9999 }) => { const f = useCurrentFrame(); return <AbsoluteFill><SipTrunkingPage dim toast={f >= createAt ? "Inbound trunk created successfully" : undefined} drawer={<CreateTrunkDrawer showPlatform v2 platform={XAI} name="xAI" uri={f >= filledAt ? "xAI" : ""} uriAddress={ADDR} />} /></AbsoluteFill>; };
// connect the number: Phone Numbers → the number → Application Type: SIP Trunk → SIP Inbound Trunk: xAI → Save changes
const PF = `${INTER_FAMILY}, sans-serif`; const PINK = "#0f1117"; const PHAIR = "rgba(15,17,23,0.12)";
const PRadio: React.FC<{ on?: boolean; children: React.ReactNode }> = ({ on, children }) => <div style={{ display: "flex", alignItems: "center", gap: 12, fontSize: 17, color: PINK }}><span style={{ width: 20, height: 20, borderRadius: 10, border: `2px solid ${on ? PINK : "#c3c6cf"}`, display: "inline-flex", alignItems: "center", justifyContent: "center" }}>{on ? <span style={{ width: 10, height: 10, borderRadius: 5, background: PINK }} /> : null}</span>{children}</div>;
export const NumberSipModal: React.FC<{ sip?: boolean; open?: boolean; hover?: boolean; picked?: boolean; saving?: boolean }> = ({ sip, open, hover, picked, saving }) => (
  <div style={{ position: "absolute", left: 1170, top: 16, width: 730, height: 1048, borderRadius: 18, background: "#fff", boxShadow: "0 30px 90px rgba(15,17,23,0.28)", padding: "30px 34px", fontFamily: PF, color: PINK }}>
    <div style={{ display: "flex", alignItems: "center" }}><span style={{ fontSize: 24, fontWeight: 700 }}>Configure Number</span><span style={{ marginLeft: "auto", fontSize: 20 }}>✕</span></div>
    <div style={{ marginTop: 26, display: "flex", alignItems: "center", gap: 14 }}><span style={{ width: 38, height: 26, borderRadius: 4, background: "linear-gradient(#b22234 0 50%, #fff 50%)", position: "relative", overflow: "hidden" }}><span style={{ position: "absolute", left: 0, top: 0, width: 16, height: 14, background: "#3c3b6e" }} /></span><div><div style={{ fontSize: 17, fontWeight: 600 }}>{NUMBER}</div><div style={{ fontSize: 14, color: "#6b7280" }}>North Dakota, United States</div></div></div>
    <div style={{ marginTop: 22, fontSize: 16, fontWeight: 600 }}>Number Type</div><div style={{ fontSize: 16 }}>Local</div>
    <div style={{ marginTop: 18, fontSize: 16, fontWeight: 600 }}>Capabilities</div><div style={{ marginTop: 8, display: "flex", gap: 8 }}>{["Voice", "SMS"].map((c) => <span key={c} style={{ fontSize: 14, fontWeight: 600, background: "#f1f2f4", borderRadius: 6, padding: "5px 10px" }}>{c}</span>)}</div>
    <div style={{ marginTop: 18, fontSize: 15, fontWeight: 600 }}>Alias</div><div style={{ marginTop: 8, height: 46, borderRadius: 10, border: `1px solid ${PHAIR}` }} />
    <div style={{ marginTop: 18, fontSize: 15, fontWeight: 600 }}>Application Type</div>
    <div style={{ marginTop: 10, display: "flex", gap: 34 }}><PRadio on={!sip}>AI Agents</PRadio><PRadio>Application</PRadio><PRadio on={sip}>SIP Trunk</PRadio></div>
    {sip ? <><div style={{ marginTop: 18, fontSize: 15, fontWeight: 600 }}>SIP Inbound Trunk</div>
      <div style={{ position: "relative" }}>
        <div style={{ marginTop: 8, height: 48, borderRadius: 10, border: `1.5px solid ${open ? PINK : PHAIR}`, display: "flex", alignItems: "center", padding: "0 14px", fontSize: 16, color: picked ? PINK : "#9aa0ac" }}>{picked ? "xAI" : "Select inbound trunk"}<span style={{ marginLeft: "auto", color: "#9aa0ac" }}>⌄</span></div>
        {open ? <div style={{ position: "absolute", left: 0, right: 0, top: 62, borderRadius: 12, border: `1px solid ${PHAIR}`, background: "#fff", boxShadow: "0 18px 50px rgba(15,17,23,0.16)", overflow: "hidden", zIndex: 2 }}><div style={{ padding: "12px 16px", fontSize: 15, color: "#9aa0ac", borderBottom: `1px solid ${PHAIR}` }}>Search...</div><div style={{ padding: "11px 16px", fontSize: 15.5, background: hover ? "#f4f5f7" : "#fff" }}>xAI</div></div> : null}
      </div></> : <><div style={{ marginTop: 18, fontSize: 15, fontWeight: 600 }}>Associated Call Agent Flow (Optional)</div><div style={{ marginTop: 8, height: 48, borderRadius: 10, border: `1px solid ${PHAIR}`, display: "flex", alignItems: "center", padding: "0 14px", fontSize: 16, color: "#9aa0ac" }}>Select call agent<span style={{ marginLeft: "auto" }}>⌄</span></div></>}
    <div style={{ marginTop: 18, fontSize: 15, fontWeight: 600 }}>Sub Account</div><div style={{ marginTop: 8, height: 48, borderRadius: 10, border: `1px solid ${PHAIR}`, display: "flex", alignItems: "center", padding: "0 14px", fontSize: 16, color: "#9aa0ac" }}>Select sub account<span style={{ marginLeft: "auto" }}>⌄</span></div>
    <div style={{ position: "absolute", left: 34, right: 34, bottom: 30, display: "flex", justifyContent: "space-between" }}><span style={{ fontSize: 15, fontWeight: 600, color: "#b42318", border: "1px solid #b42318", borderRadius: 10, padding: "12px 18px" }}>Delete Number</span><span style={{ fontSize: 15, fontWeight: 600, color: "#fff", background: saving ? "#323dfe" : PINK, borderRadius: 10, padding: "12px 18px" }}>Save changes</span></div>
  </div>);
export const PlNumberBeat: React.FC<{ modalAt: number; sipAt: number; openAt: number; pickAt: number; saveAt: number }> = ({ modalAt, sipAt, openAt, pickAt, saveAt }) => { const f = useCurrentFrame(); const saved = f >= saveAt + 12; return <AbsoluteFill><NewConsoleShell activeNav="Phone Numbers" topBar="live"><PhoneNumbersScreen rows={[[NUMBER, "", "North Dakota, United States", saved ? "SIP Trunk · xAI" : "—"]]} rowClickAt={modalAt - 10} /></NewConsoleShell>{f >= modalAt && !saved ? <><div style={{ position: "absolute", inset: 0, background: "rgba(15,17,23,0.32)" }} /><NumberSipModal sip={f >= sipAt} open={f >= openAt && f < pickAt} hover={f >= openAt + 8} picked={f >= pickAt} saving={f >= saveAt} /></> : null}{saved ? <div style={{ position: "absolute", right: 40, top: 96, background: "#fff", borderRadius: 12, boxShadow: "0 18px 50px rgba(15,17,23,0.18)", padding: "14px 18px", display: "flex", alignItems: "center", gap: 12, fontFamily: PF, fontSize: 15 }}><span style={{ color: "#16a34a", fontWeight: 700 }}>✓</span><div><div style={{ fontWeight: 600 }}>Success</div><div style={{ color: "#6b7280", fontSize: 13.5 }}>Number updated successfully</div></div></div> : null}</AbsoluteFill>; };
export const PlDoneBeat: React.FC = () => <AbsoluteFill><SipTrunkingPage rows={[{ name: "xAI", uri: "xAI", numbers: 1 }]} toast="Inbound trunk created successfully" /></AbsoluteFill>;

// ---- xAI ----
export const XaVoiceAgentsBeat: React.FC<{ hoverAt: number; modalAt: number }> = ({ hoverAt, modalAt }) => { const f = useCurrentFrame(); return <AbsoluteFill><VoiceAgentsPage hover={f >= hoverAt ? "Customer Support" : ""} modal={f >= modalAt ? <BuildModal chat={[{ at: modalAt + 4, who: "you", text: "I want to build a Customer Support agent." }, { at: modalAt + 22, who: "thinking" }]} /> : null} /></AbsoluteFill>; };
export const XaBuiltBeat: React.FC = () => <AbsoluteFill><VoiceAgentsPage modal={<BuildModal chat={[{ at: 0, who: "you", text: "Athena Pottery. No website yet. Take a message with the caller's name and callback number." }, { at: 0, who: "bot", text: "Athena Pottery customer support agent that collects name and callback number for custom order appointments. I'll build it now." }, { at: 8, who: "bot", text: "Your Athena Pottery support agent is almost ready. It collects name and callback number for custom order appointments during business hours (Monday to Friday, 8 AM to 5 PM CST)." }]} card cardAt={14} />} /></AbsoluteFill>;
export const XaAgentBeat: React.FC<{ voice?: boolean }> = ({ voice }) => <AbsoluteFill><AgentPage tab="Configuration">{voice ? <ConfigurationVoiceBody /> : <ConfigurationBody />}</AgentPage></AbsoluteFill>;
export const XaDeploymentBeat: React.FC<{ rows?: boolean; toast?: boolean }> = ({ rows, toast }) => <AbsoluteFill><AgentPage tab="Deployment" toast={toast ? `${NUMBER.replace("+1 701 719 8695", "+1 (701) 719-8695")} connected and assigned to this agent.` : undefined}><DeploymentBody rows={rows ? [{ name: "Athena", number: "+1 (701) 719-8695", by: "Direct SIP", when: "a few seconds ago" }] : []} /></AgentPage></AbsoluteFill>;
export const XaNumberModalBeat: React.FC<{ tabAt: number; nameFrom: number; nameUntil: number; numFrom: number; numUntil: number; ipsFrom?: number }> = ({ tabAt, nameFrom, nameUntil, numFrom, numUntil, ipsFrom = 9999 }) => {
  const f = useCurrentFrame();
  return <AbsoluteFill><AgentPage tab="Deployment" modal={<NewNumberModal tab={f >= tabAt ? "Direct SIP" : "Provisioned numbers"} name={type(f, "Athena", nameFrom, nameUntil)} typingName={f >= nameFrom && f < numFrom} number={type(f, "+17017198695", numFrom, numUntil)} typingNumber={f >= numFrom && f < numUntil + 12} ips={f >= ipsFrom ? Math.min(14, 1 + Math.floor((f - ipsFrom) / 5)) : 0} />}><DeploymentBody rows={[]} /></AgentPage></AbsoluteFill>;
};
